// SAMPLE DATA ONLY. Replace with verified records from the official jobs database later.
const JOBS = [
  {id:"demo-001",post:"Assistant Professor – Political Science",department:"Himachal Pradesh Public Service Commission",source:"HPPSC",qualification:"Post Graduation",subject:"Political Science",criteria:"Master's degree; NET/SET or applicable exemption (illustrative)",deadline:"2026-10-20",status:"eligible",reason:"Sample match only. Check the official advertisement.",notificationUrl:"",applyUrl:""},
  {id:"demo-002",post:"Junior Office Assistant (IT)",department:"Himachal Pradesh Rajya Chayan Aayog",source:"HPRCA",qualification:"12th",subject:"Any",criteria:"Qualification and typing criteria as per notice (illustrative)",deadline:"2026-10-08",status:"review",reason:"Typing/skill criteria and exact qualification need verification.",notificationUrl:"",applyUrl:""},
  {id:"demo-003",post:"Constable – General Duty",department:"Himachal Pradesh Police",source:"HP Police",qualification:"12th",subject:"Any",criteria:"Education, physical standards and age rules apply (illustrative)",deadline:"2026-10-14",status:"review",reason:"Physical standards and category-wise age rules need verification.",notificationUrl:"",applyUrl:""},
  {id:"demo-004",post:"Clerk",department:"Himachal Pradesh High Court",source:"HP High Court",qualification:"Graduation",subject:"Any",criteria:"Graduation and computer/typing requirements as notified (illustrative)",deadline:"2026-09-30",status:"noteligible",reason:"This sample is marked for demonstration; verify actual requirements.",notificationUrl:"",applyUrl:""},
  {id:"demo-005",post:"Combined Graduate Level – Sample Listing",department:"Staff Selection Commission",source:"Central Govt",qualification:"Graduation",subject:"Any",criteria:"Post-specific age and qualification rules apply (illustrative)",deadline:"2026-10-25",status:"eligible",reason:"Sample match only; check official SSC notification.",notificationUrl:"",applyUrl:""},
  {id:"demo-006",post:"Trained Graduate Teacher – Sample Listing",department:"Himachal Pradesh recruitment",source:"HPRCA",qualification:"Graduation",subject:"Any",criteria:"Subject-specific degree and teacher training requirements apply",deadline:"2026-10-02",status:"noteligible",reason:"Subject and teacher-training criteria not confirmed in demo profile.",notificationUrl:"",applyUrl:""}
];
