const JOBS = [
  {
    "id": "hppsc-63-9-2026",
    "post": "Agriculture Development Officer Group-A (Job-Trainee)",
    "department": "Department of Agriculture, Himachal Pradesh",
    "source": "HPPSC",
    "qualification": "B.Sc. Agriculture (4-year degree) and M.Sc. Agriculture (2nd class) from a recognised institution",
    "subject": "Agriculture",
    "criteria": "Desirable: M.Sc. Agriculture 1st class or above. Knowledge of Himachal Pradesh customs, manners and dialects, and suitability for appointment under peculiar conditions of the State.",
    "deadline": "2026-10-22",
    "status": "review",
    "reason": "Eligibility and application deadline not yet verified.",
    "notificationUrl": "https://hppsc.hp.gov.in/CommonControls/CMSFileView?qs=oeMK915q2HkdpWSZ%2B0aaIFmLDoF0cTjGvKykbXugJ5FH4sUacllacTF%2B5RqdIHDUbyy0Z1o%2FJ5mdBZRhOdQiJ2dT4h8rHe34qs%2FBwPNGPmM%3D",
    "applyUrl": "",
    "publishedDate": "2026-09-25"
  },
  {
    "id": "hppsc-61-9-2026",
    "post": "Assistant Professor (Anthropology)",
    "department": "Himachal Pradesh Public Service Commission",
    "source": "HPPSC",
    "qualification": "Master’s degree in the relevant subject with at least 55% marks from a recognised Indian or equivalent foreign university; NET/SET/SLET required, subject to notified Ph.D. exemptions.",
    "subject": "Anthropology",
    "criteria": "Specified 5% marks relaxation for eligible reserved categories and PwD candidates. Desirable: Knowledge of Himachal Pradesh customs, manners and dialects, and suitability for appointment under conditions prevailing in the State.",
    "deadline": "2026-10-16",
    "status": "review",
    "reason": "Eligibility and application deadline not yet verified.",
    "notificationUrl": "https://hppsc.hp.gov.in/CommonControls/CMSFileView?qs=oeMK915q2HkdpWSZ%2B0aaIFmLDoF0cTjGvKykbXugJ5FH4sUacllacTF%2B5RqdIHDUTVUe0nCIKKU9jLyhGEya0GRp2qQXO1kujMvupKhWlFw%3D",
    "applyUrl": "",
    "publishedDate": "2026-09-19"
  },
  {
    "id": "hppsc-62-9-2026",
    "post": "Medical Officer (General Wing)",
    "department": "Himachal Pradesh Public Service Commission",
    "source": "HPPSC",
    "qualification": "Check official notification",
    "subject": "Medical",
    "criteria": "Eligibility and age criteria as per official advertisement.",
    "deadline": "",
    "status": "review",
    "reason": "Eligibility and application deadline not yet verified.",
    "notificationUrl": "https://hppsc.hp.gov.in/CommonControls/CMSFileView?qs=oeMK915q2HkdpWSZ%2B0aaIFmLDoF0cTjGvKykbXugJ5FH4sUacllacTF%2B5RqdIHDU8OVHeK1TpVx4SlpZJoOUOt5MFxW3W1BbDCF2vzmM4nE%3D",
    "applyUrl": "",
    "publishedDate": "2026-09-19"
  },
  {
    "id": "hppsc-60-9-2026",
    "post": "Deputy Director Sainik Welfare",
    "department": "Department of Sainik Welfare, Himachal Pradesh",
    "source": "HPPSC",
    "qualification": "Check official notification",
    "subject": "Sainik Welfare",
    "criteria": "Eligibility and age criteria as per official advertisement.",
    "deadline": "",
    "status": "review",
    "reason": "Eligibility and application deadline not yet verified.",
    "notificationUrl": "https://hppsc.hp.gov.in/CommonControls/CMSFileView?qs=oeMK915q2HkdpWSZ%2B0aaIFmLDoF0cTjGvKykbXugJ5FH4sUacllaccC7RwbeCT5iTamqZcnA2%2FNq8xwFR2KAdkQfKNO0v39KpMehI%2FsmduU%3D",
    "applyUrl": "",
    "publishedDate": "2026-09-02"
  },
  {
    "id": "hppsc-59-8-2026",
    "post": "HP Administrative Services Combined Competitive Examination 2026",
    "department": "Himachal Pradesh Public Service Commission",
    "source": "HPPSC",
    "qualification": "Check official notification",
    "subject": "Any",
    "criteria": "Eligibility and age criteria as per official advertisement.",
    "deadline": "",
    "status": "review",
    "reason": "Eligibility and application deadline not yet verified.",
    "notificationUrl": "https://hppsc.hp.gov.in/CommonControls/CMSFileView?qs=oeMK915q2HkdpWSZ%2B0aaIFmLDoF0cTjGvKykbXugJ5FH4sUacllacYlnRK0MeZGEfxeUsdEM2p69nc6WDWdQBhIBr3TooKs4EQ87JuUdBNI%3D",
    "applyUrl": "",
    "publishedDate": "2026-08-26"
  }
];
